### ISSUE TITLE
[FEATURE REQUEST] How change path to lib/main.dart when runing flutter pub run msix:create?

### ISSUE THREAD

**Issue by fatsolko** [YehudaKremer/msix#146]
### :speech_balloon: Description
my  lib/main.dart located in lib/environment/main_%FLUTTER_BUILD_ENV%.dart

How change path to him when running flutter pub run msix:create?
```
flutter pub run msix:create
running "flutter build windows"...      /-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\ 
Downloading windows-x64/windows-x64-flutter tools...               11.5s
Downloading windows-x64/flutter-cpp-client-wrapper tools...        166ms
Downloading windows-x64-profile/windows-x64-flutter tools...        10.3s
Downloading windows-x64-release/windows-x64-flutter tools...         9.3s
Unhandled exception:
Target file "lib\main.dart" not found.
#0      WindowsBuild.build (package:msix/src/windows_build.dart:28:7)
<asynchronous suspension>
#1      Msix._buildMsixFiles (package:msix/msix.dart:104:31)
<asynchronous suspension>
#2      Msix._createMsix (package:msix/msix.dart:99:5)
<asynchronous suspension>
#3      Msix.create (package:msix/msix.dart:58:5)
<asynchronous suspension>
#4      main (file:///C:/Users/ContainerAdministrator/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/msix-3.6.2/bin/create.dart:4:3)
<asynchronous suspension>
pub finished with exit code 255
```

**Comment by YehudaKremer** [comment]
Hello

You can try edit "windows\flutter\ephemeral\generated_config.cmake" file:
![image](https://user-images.githubusercontent.com/946652/183770072-e15b9f54-31f0-493c-8d3d-334fbaf35785.png)

This issue is related to the `flutter windows build` command, not the msix package commands.

**Comment by fatsolko** [comment]
![изображение](https://user-images.githubusercontent.com/76652885/183841455-e02c1031-5760-4453-bf2d-14b5e8603d3d.png)
doesn't help

**Comment by YehudaKremer** [comment]
Sorry @fatsolko 

Try: `flutter build windows -t  lib/environment/main_dev.dart "&" flutter pub run msix:create --build-windows false`

**Comment by fatsolko** [comment]
![изображение](https://user-images.githubusercontent.com/76652885/183868196-96b9450a-63a6-4cec-999e-cbdda890f103.png)
It works, thank you!

**Comment by YehudaKremer** [comment]
Glad to hear it @fatsolko 

Also, please check out my comment: https://github.com/YehudaKremer/msix/issues/147#issuecomment-1210324268
