### ISSUE TITLE
[BUG] No certificates were found that met all the given criteria.

### ISSUE THREAD

**Issue by nice2cu1** [YehudaKremer/msix#150]
### :information_source: Info

**Version: `v3.6.3`**

### :speech_balloon: Description

I created my own certificate according to the documentation provided by Microsoft, it didn&#39;t work when I brought in msix, I don&#39;t know what I&#39;m doing wrong
```
PS D:\Document\FlutterProjects\super3gifts> flutter pub run msix:create -v
[  +67 ms] executing: [D:\Application\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +110 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] executing: [D:\Application\flutter/] git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[  +98 ms] Exit code 0 from: git tag --points-at f1875d570e39de09040c8f79aa13cc56baab8db1
[   +1 ms] 3.0.5
[   +9 ms] executing: [D:\Application\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +87 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [D:\Application\flutter/] git ls-remote --get-url origin
[  +81 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +363 ms] Unable to locate an Android SDK.
[   +4 ms] executing: [D:\Application\flutter/] git rev-parse --abbrev-ref HEAD
[  +79 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +96 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust thissource!
[  +74 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +71 ms] Using D:\Application\flutter\.pub-cache for the pub cache.
[        ] executing: D:\Application\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub run msix:create -v
[     0.022s] parsing cli arguments
[     0.183s] validating config values
[     0.196s] running "flutter build windows"...
[    15.126s] building msix files...
[    15.127s] validating build files
[    15.135s] cleaning temporary files
[    15.147s] create app icons
[    15.154s] generating icons
[    17.952s] copying VC libraries
[    17.972s] getting certificate publisher
[    18.537s] generate appx manifest
[    18.545s] generate package resource indexing files
[    18.693s] packing msix files...
[    18.694s] packing
[    20.500s] cleaning temporary files
[    20.960s] signing
[    21.067s]
Unhandled exception:
SignTool Error: No certificates were found that met all the given criteria.

#0      SignTool.sign (package:msix/src/sign_tool.dart:155:9)
<asynchronous suspension>
#1      Msix._packMsixFiles (package:msix/msix.dart:132:7)
<asynchronous suspension>
#2      Msix._createMsix (package:msix/msix.dart:100:5)
<asynchronous suspension>
#3      Msix.create (package:msix/msix.dart:58:5)
<asynchronous suspension>
#4      main (file:///D:/Application/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/msix-3.6.3/bin/create.dart:4:3)
<asynchronous suspension>
[+22550 ms] "flutter run" took 22,746ms.
[   +5 ms] pub finished with exit code 255
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +256 ms] ensureAnalyticsSent: 254ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 255
```

### :scroll: Pubspec.yaml

```
msix_config:
  display_name: super3gifts
  identity_name: com.nice2cu1.super3gifts
  msix_version: 1.0.0.0
  logo_path: C:\Users\VH\Desktop\icon.png
  capabilities: internetClient 
  certificate_path: C:\Users\VH\Desktop\super3gifts.pfx
  certificate_password: nice2cu1
```

**Comment by nice2cu1** [comment]
I found my mistake, I created the wrong certificate.

**Comment by YehudaKremer** [comment]
good work!

**Comment by syahrezafauzi** [comment]
Follow this step to create SelfSignedCertificate (powershell):
https://stackoverflow.com/a/47144138

1. Create Certificate
<pre>$cert = New-SelfSignedCertificate -DnsName www.yourwebsite.com -Type CodeSigning -CertStoreLocation Cert:\CurrentUser\My</pre>

2. Set the password
<pre>$CertPassword = ConvertTo-SecureString -String "my_passowrd" -Force -AsPlainText</pre>

3. Export
<pre>Export-PfxCertificate -Cert "cert:\CurrentUser\My\$($cert.Thumbprint)" -FilePath "d:\selfsigncert.pfx" -Password $CertPassword</pre>

then run create again with that new exported certificate, msix created.
hope help someone.
