### ISSUE TITLE
[BUG]  

### ISSUE THREAD

**Issue by kiaxseventh** [YehudaKremer/msix#257]
### :information_source: Info

**Version: `e.g. v2.8.15`**

### :speech_balloon: Description

**Hello, I have created a PFX file using the instructions provided at the following link:

[my link]

However, when building the MSIX file, I encounter the following error after being prompted for the relevant certificate_path:<br />
dart run msix:create
running "flutter build windows"...     52.9s
building msix files...                 31.5s
SignTool Error: An unexpected internal error has occurred.

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
#1      SignTool.sign (package:msix/src/sign_tool.dart:247:9)
<asynchronous suspension>
#2      Msix._packMsixFiles (package:msix/msix.dart:149:7)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:103:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:59:5)
<asynchronous suspension>
#5      main (file:///C:/Users/myuser/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.16.7/bin/create.dart:4:3)
<asynchronous suspension>
<br />

**Comment by Ksardias** [comment]
I had this same issue,  I change the values i write after this comand `openssl req -new -key mykeyname.key -out mycsrname.csr`

**Comment by Levi-Lesches** [comment]
Can you post your configuration file? It's possible one of your signing options is invalid.
