### ISSUE TITLE
[BUG] Error after "dart run msix:create" command

### ISSUE THREAD

**Issue by andregusmao** [YehudaKremer/msix#260]
Version: 3.16.7

After command bellow, occurs the next error message:

Building package executable... (2.9s)
Built msix:create.
Unhandled exception:
type 'String' is not a subtype of type 'int' of 'index'
#0      Configuration.getConfigValues (package:msix/src/configuration.dart:170:54)
<asynchronous suspension>
#1      Msix._initConfig (package:msix/msix.dart:97:5)
<asynchronous suspension>
#2      Msix.create (package:msix/msix.dart:58:5)
<asynchronous suspension>
#3      main (file:///C:/Users/andre.gusmao/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.16.7/bin/create.dart:4:3)
<asynchronous suspension>

**Comment by Levi-Lesches** [comment]
Can you try again with version 3.16.8 and see if you still get this issue?

**Comment by MasIzzudin** [comment]
> Any update?

I got this issue when adding configuration in my pubscpec.yaml
