### ISSUE TITLE
[BUG] when provided pfx and passwd, it still require to confirm the certificate install 

### ISSUE THREAD

**Issue by Mon-ius** [YehudaKremer/msix#286]
Inside github action, when run
```sh
dart run msix:create -c "signingCert.pfx" -p ${{ secrets.WINDOWS_PFX_PASSWD }}
```

it returns the error that,
```sh
Run dart run msix:create -c "signingCert.pfx" -p ***
running "flutter build windows"...      /-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\16.6s
building msix files...                  /-\|/-0.4s
packing msix files...                   /-\|/-\|/-\|/-\|/-\|/-\|/-\|/ 

Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<String>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:85:41)
#1      Prompter.prompt.<anonymous closure>.<anonymous closure> (package:console/src/prompt.dart:222:19)
#2      new Future.<anonymous closure> (dart:async/future.dart:258:40)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:[12](https://github.com/LaoWangFantasy/click/actions/runs/12335929689/job/34427918336#step:11:13))
Do you want to install the certificate: "signingCert.pfx" ? (y/N) 
Error: Process completed with exit code 1.
```

However, as described inside the doc,
> Note: By default, the MSIX package will install the certificate on your machine.

It should be fixed to not prompt such message for confirmations.

**Comment by pisolofin** [comment]
I had the same problem, but I solved it by skipping the certificate installation via `msix`.
I simply called `msix:create` with  `--install-certificate false`

`run dart run msix:create -c "signingCert.pfx" -p *** --install-certificate false`

You don't need to install certificate to sign the installer.

**Comment by Mon-ius** [comment]
@pisolofin you are right. But it should provide an option to skip

**Comment by pisolofin** [comment]
For me the problem was that I ran the command on the Azure pipeline machine and I can't confirm the certificate installation.
If I ran it on my PC but without the certificate installed, msix asks me for confirmation to install the certificate.
 The solution was skip certificate installation.

**Comment by Mon-ius** [comment]
> For me the problem was that I ran the command on the Azure pipeline machine and I can't confirm the certificate installation.

Same here. As I said previously, it does not provide an option as expected, so it should be a bug.
